[package]
name = "movies-api-tsv-parser"
version = "0.0.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "movietsv"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
serde-aux = "4.6.0"
serde_json = "1"
thiserror = "2"

[dependencies.uuid]
version = "1.16.0"
features = [
  "v4",                # Lets you generate random UUIDs
  "serde",
  "fast-rng",          # Use a faster (but still sufficiently random) RNG
  "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
