[application]
port = 3001
host = "0.0.0.0"
base_url = "http://0.0.0.0"
api_version = 0

[database]
host = "127.0.0.1"
port = 9969
username = "postgres"
password = "password"
database_name = "imdb_movies_db"
require_ssl = false
